name: Deploy to Simply
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '23.x'
    - name: Install npm dependencies
      run: npm install
    - name: Populate dotenv
      run: |
          touch .env
          echo SMTP_HOST="websmtp.simply.com" >> .env
          echo SMTP_PORT="587" >> .env
          echo SMTP_SECURE="true" >> .env
          echo SMTP_USER="info@gonow.dk" >> .env
          echo SMTP_PASS=${{ secrets.MAIL_PASSWORD }} >> .env
          echo INFO_TO="info@gonow.dk" >> .env
          echo FROM_EMAIL="info@gonow.dk" >> .env
          echo PORT="3001" >> .env
          cat .env
    - name: Run build task
      run: npm run build --if-present
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: "public_html/"
          EXCLUDE: "/dist/, /node_modules/"
